# Generated by Django 6.0.6 on 2026-06-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticDeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('AUTOREFRACTOR', 'Autorefractor'), ('OCT_SCANNER', 'Optical Coherence Tomography (OCT) Scanner'), ('TONOMETER', 'Tonometer (Intraocular Pressure)'), ('PENTACAM', 'Pentacam / Corneal Topographer')], max_length=50)),
                ('measured_at', models.DateTimeField()),
                ('raw_data_json', models.JSONField(help_text="Structured measurements from the device (e.g. {'IOP_OD': 14, 'IOP_OS': 15})")),
                ('scan_file', models.FileField(blank=True, help_text='Raw scanned file PDF/Image', null=True, upload_to='scans/')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_type', models.CharField(choices=[('TELECONSULTATION', 'Remote Video Consultation'), ('PHYSICAL_EXAM', 'Physical Exam'), ('DIAGNOSTIC_SCAN', 'Physical Diagnostic / Scan'), ('SURGERY', 'In-Person Surgery / Procedure')], default='TELECONSULTATION', max_length=30)),
                ('chief_complaint', models.TextField()),
                ('diagnosis_codes', models.CharField(blank=True, help_text='ICD-10 codes separated by commas', max_length=100, null=True)),
                ('treatment_plan', models.TextField()),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encrypted_clinical_notes', models.BinaryField(blank=True, help_text='Ciphertext of detailed clinical examinations', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(help_text='e.g. 1 drop, 500mg', max_length=50)),
                ('frequency', models.CharField(help_text='e.g. Twice daily, Once every 4 hours', max_length=100)),
                ('duration_days', models.IntegerField(default=7)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='General instructions', null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_hash', models.CharField(blank=True, help_text="SHA-256 hash representing doctor's digital signature", max_length=256, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefractionPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_sphere', models.DecimalField(decimal_places=2, default=0.0, help_text='Sphere (SPH)', max_digits=5)),
                ('od_cylinder', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Cylinder (CYL)', max_digits=5, null=True)),
                ('od_axis', models.IntegerField(blank=True, help_text='Axis (0-180)', null=True)),
                ('od_add', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Reading Add', max_digits=5, null=True)),
                ('os_sphere', models.DecimalField(decimal_places=2, default=0.0, help_text='Sphere (SPH)', max_digits=5)),
                ('os_cylinder', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Cylinder (CYL)', max_digits=5, null=True)),
                ('os_axis', models.IntegerField(blank=True, help_text='Axis (0-180)', null=True)),
                ('os_add', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Reading Add', max_digits=5, null=True)),
                ('pupillary_distance', models.DecimalField(blank=True, decimal_places=1, help_text='PD in mm', max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(help_text="Key-value pair of symptoms input by patient, e.g. {'blurry_vision': true, 'pain_level': 5}")),
                ('urgency_level', models.CharField(choices=[('LOW', 'Low Urgency'), ('MEDIUM', 'Medium Urgency'), ('HIGH', 'High Urgency'), ('EMERGENCY', 'Immediate Action Required')], default='LOW', max_length=20)),
                ('ai_recommendation', models.TextField(blank=True, help_text='AI system recommendation or routing notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualAcuityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('distance_feet', models.IntegerField(default=10, help_text='Calibrated test distance (typically 10 or 20 feet)')),
                ('od_acuity', models.CharField(help_text='Oculus Dexter (Right Eye) Acuity', max_length=10)),
                ('os_acuity', models.CharField(help_text='Oculus Sinister (Left Eye) Acuity', max_length=10)),
                ('is_self_test', models.BooleanField(default=True, help_text='True if taken at home by patient; False if verified in-clinic')),
                ('device_info', models.CharField(blank=True, help_text='Screen size and browser calibration metadata', max_length=255, null=True)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
