# Generated by Django 6.0.6 on 2026-06-14 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['OPHTHALMOLOGIST', 'OPTOMETRIST']}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticdevicedata',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['OPHTHALMOLOGIST', 'OPTOMETRIST']}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_items', to='medical_records.prescription'),
        ),
        migrations.AddField(
            model_name='refractionprescription',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refraction_details', to='medical_records.prescription'),
        ),
        migrations.AddField(
            model_name='triageentry',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='triage_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visualacuitytest',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='visual_acuity_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
