# Generated by Django 6.0.6 on 2026-06-30 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationitem',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationitem',
            name='substitution_notes',
            field=models.TextField(blank=True, help_text='Pharmacist notes on substitutions or interactions', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispense_status',
            field=models.CharField(choices=[('PENDING', 'Pending Dispensation'), ('PARTIAL', 'Partially Dispensed'), ('FULFILLED', 'Fully Dispensed'), ('REJECTED', 'Rejected by Pharmacist')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PHARMACIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiagnosticTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('OCT', 'Optical Coherence Tomography (OCT)'), ('VISUAL_FIELD', 'Visual Field Test'), ('FUNDUS_PHOTO', 'Fundus Photography'), ('LAB_TEST', 'Laboratory Test')], max_length=50)),
                ('clinical_notes', models.TextField(blank=True, help_text='Reason for test or specific instructions', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_requests', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(limit_choices_to={'role__in': ['OPHTHALMOLOGIST', 'OPTOMETRIST']}, on_delete=django.db.models.deletion.CASCADE, related_name='tests_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
                ('pre_op_diagnosis', models.TextField(blank=True, null=True)),
                ('post_op_diagnosis', models.TextField(blank=True, null=True)),
                ('operation_details', models.TextField()),
                ('complications', models.TextField(blank=True, null=True)),
                ('post_op_instructions', models.TextField(blank=True, null=True)),
                ('surgery_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_note', to='medical_records.medicalrecord')),
                ('surgeon', models.ForeignKey(limit_choices_to={'role': 'OPHTHALMOLOGIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='surgeries_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
