# Generated by Django 6.0.6 on 2026-06-30 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_seed_eye_hospital_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('OPHTHALMOLOGIST', 'Ophthalmologist (Doctor)'), ('OPTOMETRIST', 'Optometrist'), ('RECEPTIONIST', 'Front Desk / Receptionist'), ('PHARMACIST', 'Pharmacist'), ('OPTICIAN', 'Optician'), ('CASHIER', 'Cashier'), ('ADMIN', 'Admin')], default='PATIENT', max_length=20),
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', '-created_at'], name='users_direc_sender__b02ade_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='users_direc_recipie_20ca8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx')],
            },
        ),
    ]
