# Generated by Django 6.0.6 on 2026-06-30 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_inventoryitem_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='axis',
            field=models.IntegerField(blank=True, help_text='Axis (0-180)', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cylinder',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cylinder (CYL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sphere',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sphere (SPH)', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='e.g. Replace nose pads, fix broken frame')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('COLLECTED', 'Collected by Patient')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'OPTICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairs_handled', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='repair_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
