# Generated by Django 6.0.6 on 2026-06-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('teleconsultation_room_id', models.CharField(blank=True, help_text='WebRTC/Agora Room Identifier for Video Calls', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('slot_type', models.CharField(choices=[('TELECONSULTATION', 'Remote Video Consultation (15 min)'), ('PHYSICAL_EXAM', 'Physical Exam (30 min)'), ('DIAGNOSTIC_SCAN', 'Physical Diagnostic / Scan (45 min)'), ('SURGERY', 'In-Person Surgery / Procedure (60+ min)')], default='TELECONSULTATION', max_length=30)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called in'), ('COMPLETED', 'Completed'), ('LEFT', 'Left without being seen')], default='WAITING', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent / Dilated Scan'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority', 'check_in_time'],
            },
        ),
    ]
