# Generated by Django 6.0.6 on 2026-06-14 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['OPHTHALMOLOGIST', 'OPTOMETRIST']}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='triage_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='medical_records.triageentry'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['OPHTHALMOLOGIST', 'OPTOMETRIST']}, on_delete=django.db.models.deletion.CASCADE, related_name='slots_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointments.appointmentslot'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['doctor', 'start_time'], name='appointment_doctor__56a3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['is_booked'], name='appointment_is_book_23eb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['slot_type'], name='appointment_slot_ty_b8e4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='appointment_patient_94a7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor'], name='appointment_doctor__649ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['status'], name='appointment_status_06f81e_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['priority'], name='appointment_priorit_dd6362_idx'),
        ),
    ]
