# Generated by Django 6.0.6 on 2026-06-29 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_slot_departments(apps, schema_editor):
    AppointmentSlot = apps.get_model('appointments', 'AppointmentSlot')
    StaffProfile = apps.get_model('users', 'StaffProfile')

    for slot in AppointmentSlot.objects.filter(department__isnull=True):
        department_id = (
            StaffProfile.objects
            .filter(user_id=slot.doctor_id, department__isnull=False)
            .values_list('department_id', flat=True)
            .first()
        )
        if department_id:
            slot.department_id = department_id
            slot.save(update_fields=['department'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('users', '0004_seed_eye_hospital_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_slots', to='users.department'),
        ),
        migrations.RunPython(backfill_slot_departments, noop_reverse),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['department'], name='appointment_departm_5246b3_idx'),
        ),
    ]
